MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  DOMAIN_ADAPTATION_ON: True
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NMS: 0.3
  DA_HEADS:
    DA_IMG_GRL_WEIGHT: 0.1
    DA_INS_GRL_WEIGHT: 0.1
    DA_IMG_LOSS_WEIGHT: 0.01
    DA_INS_LOSS_WEIGHT: 0.01
    DA_CST_LOSS_WEIGHT: 0.01
DATALOADER:
  SIZE_DIVISIBILITY: 32
DATASETS:
  TRAIN: ("DIOR_trainval",)
#  TRAIN: ("coco_2017_train",)
  SOURCE_TRAIN: ("DIOR_trainval",)
#  SOURCE_TRAIN: ("coco_2017_train",)
  TARGET_TRAIN: ("HRSID_trainval",)
#  TARGET_TRAIN: ("coco_2017_train",)
  TEST: ("HRSID_trainval",)
#  TEST: ("DIOR_trainval",)
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 1200
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1200
SOLVER:
  BASE_LR: 0.0001
#  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005
  STEPS: (100000,)
  MAX_ITER: 150000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 1
#OUTPUT_DIR: "model/end2end/para/b0001_3"
#OUTPUT_DIR: "model/end2end/a_s/no_end_3"
#OUTPUT_DIR: "model/end2end/r101/dior_hrsid_3"
#OUTPUT_DIR: "model/end2end/r50/dior_hrsid_2"
OUTPUT_DIR: "model/test"
